FROM quay.io/lyfe00011/test:beta

RUN git clone https://github.com/Thilina30599/Newbot /root/WhatsAsenaDuplicated
WORKDIR /root/WhatsAsenaDuplicated/
RUN yarn install --no-audit
CMD ["node", "bot.js"]
